package com.example.supporthub.core.demo

import android.os.Build
import androidx.annotation.RequiresApi
import androidx.compose.ui.graphics.Color
import com.example.supporthub.features.admin.AdminDashboardMetricsState
import com.example.supporthub.features.admin.AdminWorkspaceSummary
import com.example.supporthub.features.authentication.model.Role
import com.example.supporthub.features.authentication.model.User
import com.example.supporthub.features.employee.EmployeeHomeHeaderState
import com.example.supporthub.features.employee.EmployeeProfileData
import com.example.supporthub.features.employee.EmployeeProfileMetrics
import com.example.supporthub.features.employee.EmployeeProfileUiState
import com.example.supporthub.features.employee.EmployeeRecentActivityIcon
import com.example.supporthub.features.employee.EmployeeRecentActivityItem
import com.example.supporthub.features.employee.EmployeeTicketSummaryState
import com.example.supporthub.features.tickets.Ticket
import java.time.Instant

const val USE_DEMO_DATA = true

object DemoDataProvider {

    private const val DEMO_WORKSPACE = "Northwind Support"
    private const val DEMO_EMPLOYEE_UID = "emp-maya-01"
    private const val DEMO_AGENT_UID = "agent-anna-01"
    private const val DEMO_ADMIN_UID = "admin-oliver-01"

    @RequiresApi(Build.VERSION_CODES.O)
    private val baseInstant: Instant = Instant.parse("2026-07-28T06:30:00Z")

    @RequiresApi(Build.VERSION_CODES.O)
    val demoEmployeeUser: User = User(
        uid = DEMO_EMPLOYEE_UID,
        fullName = "Maya Patel",
        email = "maya.patel@northwind.example",
        phone = "+91 98765 43210",
        location = "Bengaluru, India",
        jobTitle = "Operations Analyst",
        department = "Operations",
        workspaceName = DEMO_WORKSPACE,
        requestedRole = Role.EMPLOYEE.name,
        approvedRole = Role.EMPLOYEE.name,
        status = "active",
        isWorkspaceOwner = false,
        authProvider = "email",
        createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 62L).toEpochMilli(),
        updatedAt = baseInstant.minusSeconds(60L * 60L * 6L).toEpochMilli(),
        lastLogin = baseInstant.minusSeconds(60L * 45L).toEpochMilli(),
        role = Role.EMPLOYEE.name,
        avatarUrl = null,
    )

    @RequiresApi(Build.VERSION_CODES.O)
    val demoAgentUser: User = User(
        uid = DEMO_AGENT_UID,
        fullName = "Anna Rodriguez",
        email = "anna.rodriguez@northwind.example",
        phone = "+91 99887 77665",
        location = "Hyderabad, India",
        jobTitle = "Senior Support Agent",
        department = "Customer Experience",
        workspaceName = DEMO_WORKSPACE,
        requestedRole = Role.AGENT.name,
        approvedRole = Role.AGENT.name,
        status = "active",
        isWorkspaceOwner = false,
        authProvider = "google",
        createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 94L).toEpochMilli(),
        updatedAt = baseInstant.minusSeconds(60L * 60L * 4L).toEpochMilli(),
        lastLogin = baseInstant.minusSeconds(60L * 20L).toEpochMilli(),
        role = Role.AGENT.name,
        avatarUrl = null,
    )

    @RequiresApi(Build.VERSION_CODES.O)
    val demoAdminUser: User = User(
        uid = DEMO_ADMIN_UID,
        fullName = "Oliver Grant",
        email = "oliver.grant@northwind.example",
        phone = "+91 97654 32109",
        location = "Mumbai, India",
        jobTitle = "Workspace Administrator",
        department = "IT Administration",
        workspaceName = DEMO_WORKSPACE,
        requestedRole = Role.ADMIN.name,
        approvedRole = Role.ADMIN.name,
        status = "active",
        isWorkspaceOwner = true,
        authProvider = "email",
        createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 128L).toEpochMilli(),
        updatedAt = baseInstant.minusSeconds(60L * 60L * 2L).toEpochMilli(),
        lastLogin = baseInstant.minusSeconds(60L * 10L).toEpochMilli(),
        role = Role.ADMIN.name,
        avatarUrl = null,
    )

    @RequiresApi(Build.VERSION_CODES.O)
    val demoUsers: List<User> = listOf(
        demoEmployeeUser,
        demoAgentUser,
        demoAdminUser,
        User(
            uid = "emp-jordan-02",
            fullName = "Jordan Lee",
            email = "jordan.lee@northwind.example",
            phone = "+91 91234 56780",
            location = "Pune, India",
            jobTitle = "Finance Associate",
            department = "Finance",
            workspaceName = DEMO_WORKSPACE,
            requestedRole = Role.EMPLOYEE.name,
            approvedRole = Role.EMPLOYEE.name,
            status = "active",
            isWorkspaceOwner = false,
            authProvider = "email",
            createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 40L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 9L).toEpochMilli(),
            lastLogin = baseInstant.minusSeconds(60L * 90L).toEpochMilli(),
            role = Role.EMPLOYEE.name,
        ),
        User(
            uid = "emp-priya-03",
            fullName = "Priya Nair",
            email = "priya.nair@northwind.example",
            phone = "+91 92111 44567",
            location = "Kochi, India",
            jobTitle = "Operations Associate",
            department = "Operations",
            workspaceName = DEMO_WORKSPACE,
            requestedRole = Role.EMPLOYEE.name,
            approvedRole = Role.EMPLOYEE.name,
            status = "active",
            isWorkspaceOwner = false,
            authProvider = "email",
            createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 34L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 8L).toEpochMilli(),
            lastLogin = baseInstant.minusSeconds(60L * 75L).toEpochMilli(),
            role = Role.EMPLOYEE.name,
        ),
        User(
            uid = "emp-aarav-04",
            fullName = "Aarav Sharma",
            email = "aarav.sharma@northwind.example",
            phone = "+91 93411 22334",
            location = "Delhi, India",
            jobTitle = "Business Analyst",
            department = "Strategy",
            workspaceName = DEMO_WORKSPACE,
            requestedRole = Role.EMPLOYEE.name,
            approvedRole = Role.EMPLOYEE.name,
            status = "active",
            isWorkspaceOwner = false,
            authProvider = "google",
            createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 28L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 12L).toEpochMilli(),
            lastLogin = baseInstant.minusSeconds(60L * 55L).toEpochMilli(),
            role = Role.EMPLOYEE.name,
        ),
        User(
            uid = "agent-samira-02",
            fullName = "Samira Khan",
            email = "samira.khan@northwind.example",
            phone = "+91 93456 78012",
            location = "Chennai, India",
            jobTitle = "Support Agent",
            department = "Customer Experience",
            workspaceName = DEMO_WORKSPACE,
            requestedRole = Role.AGENT.name,
            approvedRole = Role.AGENT.name,
            status = "active",
            isWorkspaceOwner = false,
            authProvider = "google",
            createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 74L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 5L).toEpochMilli(),
            lastLogin = baseInstant.minusSeconds(60L * 23L).toEpochMilli(),
            role = Role.AGENT.name,
        ),
        User(
            uid = "agent-nesh-03",
            fullName = "Nisha Verma",
            email = "nisha.verma@northwind.example",
            phone = "+91 97770 11223",
            location = "Bengaluru, India",
            jobTitle = "Support Specialist",
            department = "Customer Experience",
            workspaceName = DEMO_WORKSPACE,
            requestedRole = Role.AGENT.name,
            approvedRole = Role.AGENT.name,
            status = "away",
            isWorkspaceOwner = false,
            authProvider = "google",
            createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 56L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 7L).toEpochMilli(),
            lastLogin = baseInstant.minusSeconds(60L * 140L).toEpochMilli(),
            role = Role.AGENT.name,
        ),
        User(
            uid = "admin-meera-02",
            fullName = "Meera Joshi",
            email = "meera.joshi@northwind.example",
            phone = "+91 98811 22345",
            location = "Mumbai, India",
            jobTitle = "IT Operations Manager",
            department = "IT Administration",
            workspaceName = DEMO_WORKSPACE,
            requestedRole = Role.ADMIN.name,
            approvedRole = Role.ADMIN.name,
            status = "active",
            isWorkspaceOwner = false,
            authProvider = "email",
            createdAt = baseInstant.minusSeconds(60L * 60L * 24L * 101L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 5L).toEpochMilli(),
            lastLogin = baseInstant.minusSeconds(60L * 16L).toEpochMilli(),
            role = Role.ADMIN.name,
        ),
    )

    @RequiresApi(Build.VERSION_CODES.O)
    val demoTickets: List<Ticket> = listOf(
        Ticket(
            ticketId = "TKT-24081",
            employeeUid = demoEmployeeUser.uid,
            employeeName = demoEmployeeUser.fullName,
            employeeEmail = demoEmployeeUser.email,
            workspaceName = DEMO_WORKSPACE,
            subject = "Laptop battery draining unusually fast",
            description = "Device falls from 100% to 40% in under an hour during normal work.",
            category = "Hardware",
            priority = "High",
            status = "IN_PROGRESS",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 3L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "assigned",
            createdAt = baseInstant.minusSeconds(60L * 60L * 7L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 1L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24079",
            employeeUid = "emp-jordan-02",
            employeeName = "Jordan Lee",
            employeeEmail = "jordan.lee@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "VPN access request for remote audits",
            description = "Need VPN profile enabled for quarter-end audit access.",
            category = "Access",
            priority = "Medium",
            status = "OPEN",
            assignedAgentId = null,
            assignedAgentName = null,
            assignedAgentEmail = null,
            assignedAgentRole = null,
            assignedAgentDepartment = null,
            assignedTimestamp = null,
            assignedByAdmin = null,
            assignmentStatus = null,
            createdAt = baseInstant.minusSeconds(60L * 60L * 10L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 10L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24077",
            employeeUid = "emp-ira-03",
            employeeName = "Ira Singh",
            employeeEmail = "ira.singh@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Payroll portal showing duplicate tax deduction",
            description = "Two consecutive entries appear in the April payslip.",
            category = "Payroll",
            priority = "Critical",
            status = "RESOLVED",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 42L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "resolved",
            createdAt = baseInstant.minusSeconds(60L * 60L * 46L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 4L).toEpochMilli(),
            resolvedAt = baseInstant.minusSeconds(60L * 60L * 2L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24083",
            employeeUid = "emp-karan-04",
            employeeName = "Karan Mehta",
            employeeEmail = "karan.mehta@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Monitor flickering on docking station",
            description = "External monitor blanks every few minutes after docking.",
            category = "Hardware",
            priority = "Low",
            status = "OPEN",
            assignedAgentId = null,
            createdAt = baseInstant.minusSeconds(60L * 60L * 2L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 2L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24084",
            employeeUid = demoEmployeeUser.uid,
            employeeName = demoEmployeeUser.fullName,
            employeeEmail = demoEmployeeUser.email,
            workspaceName = DEMO_WORKSPACE,
            subject = "Slack notifications missing on desktop",
            description = "Messages arrive on mobile but not on the workstation app.",
            category = "Software",
            priority = "Medium",
            status = "IN_PROGRESS",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 5L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "assigned",
            createdAt = baseInstant.minusSeconds(60L * 60L * 8L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 30L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24085",
            employeeUid = "emp-priya-03",
            employeeName = "Priya Nair",
            employeeEmail = "priya.nair@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Email signature template not updating",
            description = "New branding should appear in the footer but old template remains.",
            category = "Software",
            priority = "Medium",
            status = "WAITING_FOR_RESPONSE",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 11L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "pending_customer",
            createdAt = baseInstant.minusSeconds(60L * 60L * 14L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 3L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24086",
            employeeUid = "emp-aarav-04",
            employeeName = "Aarav Sharma",
            employeeEmail = "aarav.sharma@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Laptop not booting after security patch",
            description = "System shows a black screen after the latest patch reboot.",
            category = "Hardware",
            priority = "Critical",
            status = "OPEN",
            assignedAgentId = null,
            createdAt = baseInstant.minusSeconds(60L * 60L * 1L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 1L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24087",
            employeeUid = "emp-jordan-02",
            employeeName = "Jordan Lee",
            employeeEmail = "jordan.lee@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Shared drive permissions missing for finance folder",
            description = "Unable to open finance reports folder on the shared drive.",
            category = "Access",
            priority = "High",
            status = "RESOLVED",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 26L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "resolved",
            createdAt = baseInstant.minusSeconds(60L * 60L * 30L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 4L).toEpochMilli(),
            resolvedAt = baseInstant.minusSeconds(60L * 60L * 2L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24088",
            employeeUid = "emp-priya-03",
            employeeName = "Priya Nair",
            employeeEmail = "priya.nair@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Timesheet portal freezing after login",
            description = "Page becomes unresponsive after credentials are entered.",
            category = "Software",
            priority = "High",
            status = "IN_PROGRESS",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 9L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "assigned",
            createdAt = baseInstant.minusSeconds(60L * 60L * 12L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 2L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24089",
            employeeUid = "emp-ira-03",
            employeeName = "Ira Singh",
            employeeEmail = "ira.singh@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Office Wi-Fi disconnecting in conference room B",
            description = "Multiple users lose connection whenever calls run longer than 10 minutes.",
            category = "Network",
            priority = "High",
            status = "WAITING_FOR_RESPONSE",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 13L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "pending_customer",
            createdAt = baseInstant.minusSeconds(60L * 60L * 18L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 4L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24090",
            employeeUid = "emp-aarav-04",
            employeeName = "Aarav Sharma",
            employeeEmail = "aarav.sharma@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Requesting temporary access to analytics sandbox",
            description = "Need access for a client presentation tomorrow morning.",
            category = "Access",
            priority = "Medium",
            status = "CLOSED",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 50L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "closed",
            createdAt = baseInstant.minusSeconds(60L * 60L * 54L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 8L).toEpochMilli(),
            resolvedAt = baseInstant.minusSeconds(60L * 60L * 6L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24091",
            employeeUid = "emp-rina-05",
            employeeName = "Rina Das",
            employeeEmail = "rina.das@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Password reset email not arriving",
            description = "Tried twice from the portal but no reset link has been delivered.",
            category = "Access",
            priority = "Low",
            status = "OPEN",
            assignedAgentId = null,
            createdAt = baseInstant.minusSeconds(60L * 60L * 6L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 6L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24092",
            employeeUid = "emp-kunal-06",
            employeeName = "Kunal Das",
            employeeEmail = "kunal.das@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Printer queue stuck on floor 4",
            description = "Documents remain queued even after restarting the print service.",
            category = "Hardware",
            priority = "Medium",
            status = "RESOLVED",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 18L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "resolved",
            createdAt = baseInstant.minusSeconds(60L * 60L * 22L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 2L).toEpochMilli(),
            resolvedAt = baseInstant.minusSeconds(60L * 60L * 1L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24093",
            employeeUid = "emp-mehul-07",
            employeeName = "Mehul Joshi",
            employeeEmail = "mehul.joshi@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "Jira board not loading on mobile hotspot",
            description = "Board spins indefinitely when connecting outside office network.",
            category = "Network",
            priority = "Critical",
            status = "IN_PROGRESS",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 4L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "assigned",
            createdAt = baseInstant.minusSeconds(60L * 60L * 9L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 1L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24094",
            employeeUid = "emp-sana-08",
            employeeName = "Sana Iyer",
            employeeEmail = "sana.iyer@northwind.example",
            workspaceName = DEMO_WORKSPACE,
            subject = "PDF export crashing in finance report tool",
            description = "App closes each time the export button is clicked.",
            category = "Software",
            priority = "High",
            status = "OPEN",
            assignedAgentId = null,
            createdAt = baseInstant.minusSeconds(60L * 60L * 13L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 13L).toEpochMilli(),
        ),
        Ticket(
            ticketId = "TKT-24095",
            employeeUid = demoEmployeeUser.uid,
            employeeName = demoEmployeeUser.fullName,
            employeeEmail = demoEmployeeUser.email,
            workspaceName = DEMO_WORKSPACE,
            subject = "Slack notifications missing on desktop",
            description = "Messages arrive on mobile but not on the workstation app.",
            category = "Software",
            priority = "Medium",
            status = "IN_PROGRESS",
            assignedAgentId = demoAgentUser.uid,
            assignedAgentName = demoAgentUser.fullName,
            assignedAgentEmail = demoAgentUser.email,
            assignedAgentRole = Role.AGENT.name,
            assignedAgentDepartment = demoAgentUser.department,
            assignedTimestamp = baseInstant.minusSeconds(60L * 60L * 5L).toEpochMilli(),
            assignedByAdmin = demoAdminUser.fullName,
            assignmentStatus = "assigned",
            createdAt = baseInstant.minusSeconds(60L * 60L * 8L).toEpochMilli(),
            updatedAt = baseInstant.minusSeconds(60L * 60L * 30L).toEpochMilli(),
        ),
    )

    fun employeeHomeHeaderState(): EmployeeHomeHeaderState = EmployeeHomeHeaderState(
        dateLabel = "TUESDAY, 28 JULY",
        greeting = "Good morning, Maya Patel",
    )

    fun employeeTicketSummaryState(): EmployeeTicketSummaryState = EmployeeTicketSummaryState(
        openCount = 2,
        inProgressCount = 2,
        resolvedCount = 1,
    )

    fun employeeRecentActivityItems(): List<EmployeeRecentActivityItem> = listOf(
        EmployeeRecentActivityItem(
            ticketId = "TKT-24081",
            displayId = "2408",
            title = "Laptop battery draining unusually fast",
            subtitle = "Assigned to Anna Rodriguez 2h ago",
            statusLabel = "IN PROGRESS",
            icon = EmployeeRecentActivityIcon.TICKET_IN_PROGRESS,
        ),
        EmployeeRecentActivityItem(
            ticketId = "TKT-24077",
            displayId = "2407",
            title = "Payroll portal showing duplicate tax deduction",
            subtitle = "Resolved today at 11:30 AM",
            statusLabel = "RESOLVED",
            icon = EmployeeRecentActivityIcon.TICKET_RESOLVED,
        ),
        EmployeeRecentActivityItem(
            ticketId = "TKT-24084",
            displayId = "2408",
            title = "Slack notifications missing on desktop",
            subtitle = "Waiting for response from support",
            statusLabel = "OPEN",
            icon = EmployeeRecentActivityIcon.TICKET_OPEN,
        ),
    )

    @RequiresApi(Build.VERSION_CODES.O)
    fun employeeProfileData(): EmployeeProfileData = EmployeeProfileData(
        user = demoEmployeeUser,
        metrics = EmployeeProfileMetrics(openTickets = 2, resolvedTickets = 3, rating = "4.8"),
    )

    @RequiresApi(Build.VERSION_CODES.O)
    fun employeeProfileUiState(): EmployeeProfileUiState = EmployeeProfileUiState(
        fullName = demoEmployeeUser.fullName,
        email = demoEmployeeUser.email,
        phone = demoEmployeeUser.phone,
        location = demoEmployeeUser.location,
        jobTitle = demoEmployeeUser.jobTitle,
        department = demoEmployeeUser.department,
        openTickets = 2,
        resolvedTickets = 3,
        rating = "4.8",
        isLoading = false,
    )

    @RequiresApi(Build.VERSION_CODES.O)
    fun adminWorkspaceSummary(): AdminWorkspaceSummary = AdminWorkspaceSummary(
        users = demoUsers,
        tickets = demoTickets,
    )
}
